export default [
  // Easy questions (1-7)
  {
    id: "q1",
    type: "multiple_choice",
    question: "What does HRM stand for?",
    options: [
      "High Revenue Model",
      "Human Resource Management",
      "Human Relations Manual",
      "Hiring and Recruitment Method",
    ],
    correctAnswer: "Human Resource Management",
    difficulty: "easy",
  },
  {
    id: "q2",
    type: "true_false",
    question: "HRM treats employees as strategic assets rather than just costs.",
    options: ["True", "False"],
    correctAnswer: "True",
    difficulty: "easy",
  },
  {
    id: "q3",
    type: "multiple_choice",
    question: "Which of these is a basic function of HR?",
    options: [
      "Selling company products",
      "Recruitment and selection",
      "Managing the company website only",
      "Designing book covers",
    ],
    correctAnswer: "Recruitment and selection",
    difficulty: "easy",
  },
  {
    id: "q4",
    type: "true_false",
    question: "Performance management is only done once a year.",
    options: ["True", "False"],
    correctAnswer: "False",
    difficulty: "easy",
  },
  {
    id: "q5",
    type: "multiple_choice",
    question: "What is the main goal of orientation for new employees?",
    options: [
      "To test their technical skills immediately",
      "To assign them the hardest tasks first",
      "To help them feel welcomed and understand the company",
      "To reduce their salary during training",
    ],
    correctAnswer: "To help them feel welcomed and understand the company",
    difficulty: "easy",
  },
  {
    id: "q6",
    type: "true_false",
    question: "Fair pay is the only factor that motivates employees.",
    options: ["True", "False"],
    correctAnswer: "False",
    difficulty: "easy",
  },
  {
    id: "q7",
    type: "multiple_choice",
    question: "What does a job description mainly contain?",
    options: [
      "The personal hobbies of the employee",
      "The company's annual profit",
      "Names of all colleagues",
      "Tasks, responsibilities, and required skills for a role",
    ],
    correctAnswer: "Tasks, responsibilities, and required skills for a role",
    difficulty: "easy",
  },

  // Medium questions (8-14)
  {
    id: "q8",
    type: "multiple_choice",
    question: "According to Bassey Anam, what is one key difference between Personnel Management and HRM?",
    options: [
      "HRM only handles payroll",
      "Personnel Management focuses on training only",
      "Personnel Management is more admin-focused while HRM is strategy-focused",
      "There is no difference",
    ],
    correctAnswer: "Personnel Management is more admin-focused while HRM is strategy-focused",
    difficulty: "medium",
  },
  {
    id: "q9",
    type: "true_false",
    question: "HR planning helps prevent situations where the company is constantly short-staffed.",
    options: ["True", "False"],
    correctAnswer: "True",
    difficulty: "medium",
  },
  {
    id: "q10",
    type: "multiple_choice",
    question: "Which motivation theory suggests that lower needs must be met before higher needs become motivators?",
    options: [
      "Taylor's Scientific Management",
      "Maslow's Hierarchy of Needs",
      "The Hawthorne Effect only",
      "Equity Theory",
    ],
    correctAnswer: "Maslow's Hierarchy of Needs",
    difficulty: "medium",
  },
  {
    id: "q11",
    type: "true_false",
    question: "In recruitment, selection comes before attracting candidates.",
    options: ["True", "False"],
    correctAnswer: "False",
    difficulty: "medium",
  },
  {
    id: "q12",
    type: "multiple_choice",
    question: "What is the main purpose of job analysis?",
    options: [
      "To increase employee salary automatically",
      "To reduce the number of employees",
      "To create company logos",
      "To understand the tasks and skills needed for a role",
    ],
    correctAnswer: "To understand the tasks and skills needed for a role",
    difficulty: "medium",
  },
  {
    id: "q13",
    type: "true_false",
    question: "Effective communication in an organisation only flows from managers to staff.",
    options: ["True", "False"],
    correctAnswer: "False",
    difficulty: "medium",
  },
  {
    id: "q14",
    type: "multiple_choice",
    question: "What is one benefit of good HR planning for staff members?",
    options: [
      "Higher workload with no support",
      "Random salary cuts",
      "Clearer career paths and reduced burnout",
      "Fewer training opportunities",
    ],
    correctAnswer: "Clearer career paths and reduced burnout",
    difficulty: "medium",
  },

  // Hard questions (15-20)
  {
    id: "q15",
    type: "multiple_choice",
    question: "Which historical study showed that attention and social relationships can boost productivity more than physical conditions?",
    options: [
      "Taylor's Time and Motion Studies",
      "The Scientific Management Experiments",
      "The Hawthorne Studies",
      "The Welfare Officer Trials",
    ],
    correctAnswer: "The Hawthorne Studies",
    difficulty: "hard",
  },
  {
    id: "q16",
    type: "true_false",
    question: "In Herzberg's Two-Factor Theory, salary and working conditions are considered motivators.",
    options: ["True", "False"],
    correctAnswer: "False",
    difficulty: "hard",
  },
  {
    id: "q17",
    type: "multiple_choice",
    question: "What is a key characteristic of good performance feedback?",
    options: [
      "It is given only once a year in a formal meeting",
      "It focuses only on what the employee did wrong",
      "It is specific, timely, and focused on improvement",
      "It compares the employee negatively with colleagues",
    ],
    correctAnswer: "It is specific, timely, and focused on improvement",
    difficulty: "hard",
  },
  {
    id: "q18",
    type: "true_false",
    question: "According to Bassey Anam, line managers play no role in day-to-day HR activities.",
    options: ["True", "False"],
    correctAnswer: "False",
    difficulty: "hard",
  },
  {
    id: "q19",
    type: "multiple_choice",
    question: "What is the main difference between training and development?",
    options: [
      "Training is only for managers",
      "Development happens only off the job",
      "There is no difference between the two",
      "Training focuses on current job skills while development prepares for future roles",
    ],
    correctAnswer: "Training focuses on current job skills while development prepares for future roles",
    difficulty: "hard",
  },
  {
    id: "q20",
    type: "true_false",
    question: "Good employee relations help reduce conflicts and increase trust in the workplace.",
    options: ["True", "False"],
    correctAnswer: "True",
    difficulty: "hard",
  },
];
